# Generated by Django 3.2.7 on 2021-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_caption_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_type',
            field=models.CharField(choices=[('raw', 'raw'), ('jpg', 'jpg')], max_length=200, null=True),
        ),
    ]
