# Generated by Django 3.2.7 on 2021-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_photo_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='Album.album_title'),
        ),
    ]
