# Generated by Django 3.2.7 on 2021-09-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_type',
            field=models.CharField(choices=[('raw', 'raw'), ('jpg', 'jpg'), ('psd', 'psd')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
