# Generated by Django 3.2.7 on 2021-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_photo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='selected',
            new_name='is_favorite',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='Homepage'),
        ),
    ]
